import calendar
miCalendario = calendar.TextCalendar()
año = int(input("\nIngrese el año: "))
print()
# print(calendar.month(año, 1))
# print(calendar.month(año, 2))
# print(calendar.month(año, 3))
# print(calendar.month(año, 4))
# print(calendar.month(año, 5))
# print(calendar.month(año, 6))
# print(calendar.month(año, 7))
# print(calendar.month(año, 8))
# print(calendar.month(año, 9))
# print(calendar.month(año, 10))
# print(calendar.month(año, 11))
# print(calendar.month(año, 12))

# print(miCalendario.formatmonth(año, mes))

print(miCalendario.formatyear(año))